## issue 94: the Combo boards, GENERATED from the hook graph.
##
## `ArtefactHooks.REGISTRY` says what each Artefact LISTENS to. `fires` on
## Items/Piece Buffs (items.gd), `power_fires`/`ability_fires` on Armies
## (armies.gd) and the derived `artefact_fires.json` say what each effect
## CAUSES. A board exists wherever those two meet:
##
##     combo(X, Y)  iff  fires(X) ∩ listens(Y) ≠ ∅
##
## DIRECTED, not "both touch the same hook" — that distinction is the whole
## slice. `on_wave_clear` has 39 Artefact listeners that never interact;
## undirected they would emit 741 pairs of noise, and directed they emit
## nothing at all, because no Item, Buff, Army or Artefact fires on_wave_clear.
## The wave does.
##
## `suppresses` is declared alongside `fires` but generates NOTHING here (user
## ruling): the anti-combo boards are a later slice. See FLAGS.

const Items := preload("res://data/items.gd")
const Armies := preload("res://scripts/armies.gd")
const ArtefactHooks := preload("res://scripts/artefact_hooks.gd")
const Tuning := preload("res://scripts/tuning.gd")

const FIRES_PATH := "res://data/artefact_fires.json"

## Artefacts are capped at 5 (Tuning.ARTEFACT_CAP_BASE), so a hook with 22
## listeners cannot be shown on one board. Chunk to the cap — one less when the
## producer is itself an Artefact and takes a slot.
const CHUNK := Tuning.ARTEFACT_CAP_BASE

## The player side carries a spread of values and an escort, so a board is
## playable rather than instantly lost; the enemies are close enough that a
## capture-driven hook is reachable in a move or two (81's bar: visible within
## a couple of moves, not twenty).
const PLAYER := [["queen", 0, 3, 1], ["rook", 0, 5, 1], ["pawn", 0, 1, 0], ["pawn", 0, 6, 0]]
const ENEMY := [["pawn", 1, 2, 4], ["pawn", 1, 4, 4], ["rook", 1, 3, 6]]

## Producers this generator did NOT give a board, because another producer of
## the same hook sorted first. Deliberate — one board per (hook, chunk) keeps
## this at ~40 entries instead of ~150 — but recorded rather than silently cut,
## and asserted non-silent by test_combos. Read it with dropped().
static var _dropped: Array = []


static var _fires_cache: Dictionary = {}


## key -> Array of hooks it fires, for the 180 Artefacts. GENERATED by
## tools/derive-artefact-fires.mjs from _dispatch's match arms — never
## hand-edited (CLAUDE.md: generated data is generated).
static func artefact_fires() -> Dictionary:
	if _fires_cache.is_empty():
		var parsed: Variant = JSON.parse_string(
			FileAccess.get_file_as_string(FIRES_PATH))
		assert(parsed is Dictionary, "artefact_fires.json did not parse as a Dictionary")
		_fires_cache = parsed
	return _fires_cache


## Every producer, as {key, name, kind, fires}. kind drives how the board holds
## it: an Item goes in `items`, a Buff rides a board piece, an Army is the run's
## own Army, an Artefact takes one of the five Artefact slots.
static func _producers() -> Array:
	var out: Array = []
	for it in Items.ITEMS:
		out.append({"key": it.key, "name": it.name, "kind": "item",
			"fires": it.get("fires", [])})
	for b in Items.PIECE_BUFFS:
		out.append({"key": b.key, "name": b.name, "kind": "buff",
			"fires": b.get("fires", [])})
	for id in Armies.CATALOG:
		var a: Dictionary = Armies.CATALOG[id]
		out.append({"key": id, "name": a.power_name, "kind": "army",
			"fires": a.get("power_fires", [])})
		out.append({"key": id, "name": a.ability_name, "kind": "army",
			"fires": a.get("ability_fires", [])})
	for key in artefact_fires():
		out.append({"key": key, "name": _titled(key), "kind": "artefact",
			"fires": artefact_fires()[key]})
	out.sort_custom(func(x: Dictionary, y: Dictionary) -> bool: return x.key < y.key)
	return out


## An Artefact's real display name, from the catalog — never a prettified key.
## `capitalize()` on the key gives "Kgb Photo Eraser" and "Seti S Red Marker",
## which are not the names of anything (the id convention, issue 58: entries key
## on ids and only ever SHOW names). Falls back to the key for a producer whose
## catalog row is gone, so a stale entry is visible rather than blank.
static func _titled(key: String) -> String:
	for e in Items.ARTEFACT_EFFECTS:
		if e.key == key:
			return e.name
	return key


## hook -> Array of Artefact keys listening on it, sorted.
static func _listeners() -> Dictionary:
	var out := {}
	for key in ArtefactHooks.REGISTRY:
		for hook in ArtefactHooks.REGISTRY[key]:
			if not out.has(hook):
				out[hook] = []
			out[hook].append(key)
	for hook in out:
		out[hook].sort()
	return out


static func all() -> Array:
	_dropped = []
	var listeners := _listeners()
	var by_hook := {}
	for p in _producers():
		for hook in p.fires:
			if not listeners.has(hook):
				continue # a hook nothing listens on produces no board
			if not by_hook.has(hook):
				by_hook[hook] = []
			by_hook[hook].append(p)

	var out: Array = []
	var hooks: Array = by_hook.keys()
	hooks.sort()
	for hook in hooks:
		var producers: Array = by_hook[hook]
		var lead: Dictionary = producers[0] # _producers() is key-sorted
		for i in range(1, producers.size()):
			_dropped.append("%s (%s) at %s" % [producers[i].name, producers[i].key, hook])
		# One Artefact slot is spent on the producer itself when it is an
		# Artefact, so the chunk that fits beside it is one smaller.
		var room: int = CHUNK - (1 if lead.kind == "artefact" else 0)
		var pool: Array = listeners[hook].duplicate()
		pool.erase(lead.key) # an Artefact never needs to be its own audience
		var chunks: int = int(ceil(float(pool.size()) / float(room)))
		for c in chunks:
			var chunk: Array = pool.slice(c * room, min((c + 1) * room, pool.size()))
			out.append(_board(hook, lead, chunk, c, chunks))
	return out


static func _board(hook: String, lead: Dictionary, chunk: Array, index: int,
		total: int) -> Dictionary:
	var board: Array = PLAYER.duplicate(true) + ENEMY.duplicate(true)
	var cfg := {
		"board": board,
		"stock": ["pawn", "pawn"],
		"gold": 400, "score": 500,
		"artefacts": chunk.duplicate(),
		"seed": abs(hash("%s|%s|%d" % [hook, lead.key, index])),
	}
	match lead.kind:
		"item":
			cfg["items"] = [lead.key]
		"buff":
			# rides the queen — the piece most likely to be doing the capturing
			board[0] = ["queen", 0, 3, 1, {"buffs": [{"key": lead.key}]}]
		"army":
			# Armies.entry() falls back to the default army on an unknown id, so
			# an unrecognised key here would silently do nothing (issue 81 hit
			# exactly that). CATALOG's own keys are the ids, so this is safe.
			cfg["army"] = lead.key
		"artefact":
			cfg["artefacts"] = [lead.key] + chunk
	var suffix := "" if total <= 1 else " (%d/%d)" % [index + 1, total]
	# menu.gd cuts at the first ":", so these join 81's hand-built "Combo"
	# section rather than starting one of their own (user ruling).
	return {"name": "Combo: %s via %s%s" % [hook, lead.name, suffix], "cfg": cfg}


## The producers all() passed over, most recent build. Empty before all() runs.
static func dropped() -> Array:
	return _dropped
