extends SceneTree
## NO-101: the four literal inv- ids (inv-sergeant, inv-arrow-pawn,
## inv-kirin-plus, inv-kirin-plus-plus) get the inversion glyph; their
## non-inverted counterparts — and everything else on the board, including
## pieces from the ten become-an-existing-piece inversion pairs, which keep
## that piece's own id — do not (Max's ruling 2026-09-16, out of scope).
##
## Boots the real "every piece type, your side" scenario (generated by
## data/scenarios_pieces.gd from pieces.json) rather than hand-rolling a
## board, so this runs against pieces the game's own setup path actually
## placed. Calls `_is_inversion_marked`, the exact predicate `_draw_piece`
## gates the glyph draw on (game.gd), so the check can never drift from what
## gets drawn. NO-100: also pins the mark's placement — centred on the tile
## via `_inv_mark_centre`, disc inside the tile, glyph white. A true pixel
## check needs a window — game.gd's own
## `_screenshot_and_quit` is commented "windowed run required" — so this is
## the headless ceiling; NO-101's PR carries a windowed screenshot as the
## visual proof.
## Run headless:  godot --headless --path game -s tests/test_board_draw.gd

const GameScript := preload("res://scripts/game.gd")
const Scenarios := preload("res://data/scenarios.gd")
const BuffLogic := preload("res://scripts/buff_logic.gd")

const INVERTED := ["inv-sergeant", "inv-arrow-pawn", "inv-kirin-plus", "inv-kirin-plus-plus"]
const COUNTERPARTS := ["sergeant", "arrow-pawn", "kirin-plus", "kirin-plus-plus"]

var fails := 0


func check(cond: bool, label: String) -> void:
	if not cond:
		push_error("FAIL: " + label)
		fails += 1
	else:
		print("ok: " + label)


func _init() -> void:
	# NO-149 renamed this scenario to "ALL PIECES (%d, your side)" — match on
	# "your side" rather than a prefix, since both ALL PIECES boards now share
	# the "ALL PIECES (" lead-in and only the tail distinguishes them.
	var matches: Array = Scenarios.all().filter(
		func(e: Dictionary) -> bool: return e.name.contains("your side"))
	check(matches.size() == 1, "exactly one 'every type, your side' scenario exists")
	if matches.size() != 1:
		quit(1)
		return
	var cfg: Dictionary = matches[0].cfg.duplicate()
	cfg.seed = 1
	GameScript.next_config = cfg
	GameScript.is_scenario = true
	var game: Node2D = load("res://scenes/Game.tscn").instantiate()
	root.add_child(game)
	await process_frame
	await process_frame

	var ids_on_board := {}
	for pos in game.board:
		ids_on_board[game.board[pos].id] = true

	for id in INVERTED:
		check(ids_on_board.has(id), "scenario board carries %s" % id)
		check(game._is_inversion_marked(id), "%s is marked" % id)
	for id in COUNTERPARTS:
		check(ids_on_board.has(id), "scenario board carries %s" % id)
		check(not game._is_inversion_marked(id), "%s (non-inverted) is NOT marked" % id)

	# NO-100 (Max's ruling 2026-09-24): the mark is a white glyph on a dark
	# disc centred on the tile — no longer NO-101's side-coloured top-right
	# corner glyph. `_inv_mark_centre` is the exact helper `_draw_piece` places
	# the disc and glyph with, so this can't drift from the draw.
	var px := Vector2(37, 53) # an arbitrary tile origin, not (0, 0)
	var t: float = game.tile
	var c: Vector2 = game._inv_mark_centre(px)
	var want := px + Vector2(t, t) / 2.0 + Vector2(0, t * game.INV_MARK_DROP)
	check(c.is_equal_approx(want) and game.INV_MARK_DROP > 0.0,
		"inversion mark is centred horizontally, dropped below the piece's face (%s vs %s)" % [c, want])
	var r: float = game._inv_mark_size() * game.INV_MARK_DISC_RATIO
	check(Rect2(px, Vector2(t, t)).encloses(Rect2(c - Vector2(r, r), Vector2(r, r) * 2)),
		"inversion mark's disc (r=%.1f) lies inside its tile (%.1f)" % [r, t])
	check(game.INV_MARK_GLYPH_COL == Color.WHITE, "inversion glyph is white, not the side colour")
	check(game.INV_MARK_DISC_COL == Color(0, 0, 0, 0.72), "inversion disc is dark, 72% alpha")

	# NO-244 (Max, 2026-09-24): up to 4 buff badges, 2 per row — the 4th must
	# not overlap the 3rd. `_buff_badge_centres` is the helper
	# `_draw_buff_badges` places them with, so this can't drift from the draw.
	var half: float = game._buff_badge_half()
	var tile_rect := Rect2(px, Vector2(t, t))
	for n in range(1, 5):
		var centres: Array[Vector2] = game._buff_badge_centres(px, n)
		var inside := centres.size() == n
		for ctr in centres:
			inside = inside and tile_rect.encloses(Rect2(ctr - Vector2(half, half), Vector2(half, half) * 2))
		check(inside, "%d buff badge(s): %d centres, every badge inside its tile (%s)" % [n, n, centres])
	var four: Array[Vector2] = game._buff_badge_centres(px, 4)
	var apart := true
	for i in 4:
		for j in range(i + 1, 4):
			apart = apart and (absf(four[i].x - four[j].x) >= half * 2 or absf(four[i].y - four[j].y) >= half * 2)
	check(apart, "4 buff badges: 4 distinct centres, no two badges overlap (%s)" % [four])
	var three: Array[Vector2] = game._buff_badge_centres(px, 3)
	check(is_equal_approx(three[2].x, (three[0].x + three[1].x) / 2.0) and three[2].y < three[0].y,
		"3 buff badges: the third sits centred above the bottom pair")

	# Stun badge (Max's ruling): red, same shape/size as a Buff badge, takes
	# a slot alongside Buffs and takes PRIORITY over the 4th when full.
	# `_badge_slots` is the exact helper `_draw_buff_badges` draws from, so
	# these checks can't drift from what actually gets drawn.
	check(game.STUN_BADGE_COL != game.BUFF_BADGE_ACCENT,
		"the stun badge's colour is distinct from the amber Buff badge colour")

	var stunned_only := {"buffs": [{"key": "stunned", "turns": 2}]}
	var stun_only_slots: Dictionary = game._badge_slots(stunned_only)
	check(stun_only_slots.glyphs == [game.STUN_BADGE_GLYPH] and stun_only_slots.stun_index == 0,
		"a stunned piece with no Buffs draws exactly one red stun badge (%s)" % [stun_only_slots])

	var no_longer_stunned := {"buffs": []} # BuffLogic._age erases "buffs" once turns reach 0
	var cleared_slots: Dictionary = game._badge_slots(no_longer_stunned)
	check(cleared_slots.stun_index == -1 and cleared_slots.glyphs.is_empty(),
		"the stun badge clears once the stun ends (%s)" % [cleared_slots])

	var three_buffs := [{"key": "shield"}, {"key": "critical"}, {"key": "taunt"}]
	var four_buffs_stunned := {"buffs": three_buffs + [{"key": "bomb"}, {"key": "stunned", "turns": 1}]}
	var priority_slots: Dictionary = game._badge_slots(four_buffs_stunned)
	var kept_glyphs: Array[String] = BuffLogic.glyphs_of({"buffs": three_buffs})
	check(priority_slots.glyphs.size() == 4 and priority_slots.stun_index == 3
			and priority_slots.glyphs[3] == game.STUN_BADGE_GLYPH
			and priority_slots.glyphs.slice(0, 3) == kept_glyphs,
		"4 Buffs + Stunned: still 4 badges total, Stun takes the 4th slot over the last Buff (%s)" % [priority_slots])

	game.queue_free()
	await process_frame

	await _merge_target_checks()

	print("---")
	if fails == 0:
		print("ALL BOARD-DRAW CHECKS OK")
	quit(1 if fails > 0 else 0)


const MERGE_PAIR := {"board": [["pawn", 0, 2, 2], ["pawn", 0, 3, 2], ["rook", 1, 7, 10]],
	"wave": 3, "gold": 300, "seed": 1} # issue 98: an unfunded board shows no partners


func _boot_pair() -> Node2D:
	GameScript.reset_boot_defaults()
	GameScript.next_config = MERGE_PAIR.duplicate(true)
	GameScript.is_scenario = true
	var g: Node2D = load("res://scenes/Game.tscn").instantiate()
	root.add_child(g)
	await process_frame
	g.animations_on = true # the local Settings file must not decide this suite
	g.autoplay = false
	return g


func _func_body(src: String, fn: String) -> String:
	var start := src.find("\nfunc %s() -> void:" % fn)
	if start < 0:
		return ""
	return src.substr(start, src.find("\nfunc ", start + 1) - start)


func _mouse(g: Node2D, tile: Vector2i, pressed: bool) -> void:
	var ev := InputEventMouseButton.new()
	ev.button_index = MOUSE_BUTTON_LEFT
	ev.pressed = pressed
	ev.position = g._tile_px(tile) + Vector2(g.tile, g.tile) / 2
	g._unhandled_input(ev)


## Max, 2026-09-26: a merge target is a pulsing yellow-orange outline plus a
## wiggle on its piece — the cyan ring is gone. `merge_target_tiles` and
## `merge_target_fx` are what `_draw` draws from, so these can't drift from it.
func _merge_target_checks() -> void:
	var g := await _boot_pair()
	g._on_tile_clicked(Vector2i(2, 2)) # select one pawn: the other is its target
	var targets: Array[Vector2i] = g.merge_target_tiles()
	check(targets.size() == 1 and targets[0] == Vector2i(3, 2),
		"the merge partner, and only it (not the selection), is a merge target (%s)" % [targets])
	var a: Dictionary = g.merge_target_fx(Vector2i(3, 2), 0.1)
	var b: Dictionary = g.merge_target_fx(Vector2i(3, 2), 0.3)
	check(a.animated and not is_equal_approx(a.width, b.width) and not is_equal_approx(a.alpha, b.alpha),
		"animations on: the outline pulses (width %.2f -> %.2f)" % [a.width, b.width])
	check(not is_equal_approx(a.angle, b.angle) and absf(a.angle) <= g.MERGE_TARGET_SHAKE_RAD
			and absf(a.offset.x) <= g.MERGE_TARGET_SHAKE_PX and (a.angle != 0.0 or b.angle != 0.0),
		"animations on: the target piece wiggles a few degrees / px (%.3f, %.3f rad)" % [a.angle, b.angle])
	check(g.COL_MERGE_TARGET == g.COL_MERGE_ORANGE and g.merge_color == g.COL_MERGE_ORANGE
			and a.color == g.COL_MERGE_ORANGE,
		"orange is the default merge target colour until Max picks")
	check(GameScript.merge_color_from(PackedStringArray(["--merge-color", "lime"])) == g.COL_MERGE_LIME
			and GameScript.merge_color_from(PackedStringArray(["--merge-color", "orange"])) == g.COL_MERGE_ORANGE
			and GameScript.merge_color_from(PackedStringArray()) == g.COL_MERGE_ORANGE,
		"--merge-color lime|orange picks the colour; no flag is orange")
	g.merge_color = g.COL_MERGE_LIME
	check(g.merge_target_fx(Vector2i(3, 2), 0.1).color == g.COL_MERGE_LIME, "a lime run outlines in lime")
	g.merge_color = g.COL_MERGE_ORANGE
	# Shaped, not a square: the outline is the silhouette shader on _merge_fx.
	var mat: Variant = g._merge_fx.material
	check(mat is ShaderMaterial and (mat as ShaderMaterial).shader.code == g.SELECT_OUTLINE_SHADER,
		"the merge target outline traces the token silhouette (outline shader on _merge_fx)")
	# _draw (the board) marks partners only by wiggling them: no cyan ring
	# (a merge_highlights loop on main, so this fails there) and no tile rect.
	var src: String = (GameScript as GDScript).source_code
	var body := _func_body(src, "_draw")
	check(body != "" and not body.contains("merge_highlights") and not body.contains("MERGE_TARGET")
			and body.contains("merge_target_tiles()"),
		"no cyan merge ring and no square outline on the board")
	var fx_body := _func_body(src, "_draw_merge_fx")
	check(fx_body.contains("draw_texture_rect_region") and not fx_body.contains("draw_rect(")
			and not fx_body.contains("draw_arc("),
		"_draw_merge_fx draws the token's silhouette only, never a rect or ring")
	g.animations_on = false
	var s1: Dictionary = g.merge_target_fx(Vector2i(3, 2), 0.1)
	var s2: Dictionary = g.merge_target_fx(Vector2i(3, 2), 0.3)
	check(not s1.animated and s1 == s2 and s1.angle == 0.0 and s1.offset == Vector2.ZERO
			and s1.width == g.MERGE_TARGET_WIDTH and s1.alpha == 1.0,
		"animations off: a static full outline, no pulse, no wiggle")
	g.animations_on = true
	g.autoplay = true
	check(not g.merge_target_fx(Vector2i(3, 2), 0.1).animated, "autoplay: static outline too")
	g.autoplay = false
	# merge by tap still works: the second pick asks, the confirm merges onto it
	g._on_tile_clicked(Vector2i(3, 2))
	check(g.pending_merge.size() == 2, "tapping the merge target asks for merge confirmation")
	g.modals.merge_confirmed.emit()
	check(g.board.has(Vector2i(3, 2)) and g.board[Vector2i(3, 2)].id == "sergeant"
			and not g.board.has(Vector2i(2, 2)),
		"tap merge: confirming promotes on the target's tile")
	check(g.merge_target_tiles().is_empty(), "no merge target left after the merge")
	g.queue_free()
	await process_frame

	# merge by drag still works: press the pawn, release on its partner
	g = await _boot_pair()
	_mouse(g, Vector2i(2, 2), true)
	check(g.drag_from == Vector2i(2, 2) and g.merge_target_tiles().size() == 1,
		"press starts a drag and outlines the partner")
	_mouse(g, Vector2i(3, 2), false)
	check(g.pending_merge.size() == 2, "dropping on the merge target asks for merge confirmation")
	g.modals.merge_confirmed.emit()
	check(g.board.has(Vector2i(3, 2)) and g.board[Vector2i(3, 2)].id == "sergeant"
			and not g.board.has(Vector2i(2, 2)),
		"drag merge: confirming promotes on the target's tile")
	g.queue_free()
	await process_frame
