extends SceneTree
## Wave Catalog data sanity — the 150 designed waves transcribed from the GDD,
## plus the generated Endless tail (151-200, NO-7 slice 1)
## (Draft v1), plus the tariff schedule that rides on them.
## Run headless:  godot --headless --path game -s tests/test_waves.gd

const Waves := preload("res://data/waves.gd")
const KingAbilities := preload("res://data/king_abilities.gd")
const GameScript := preload("res://scripts/game.gd")
const Tuning := preload("res://scripts/tuning.gd")
const WaveLogic := preload("res://scripts/wave_logic.gd")

var fails := 0


func check(cond: bool, label: String) -> void:
	if not cond:
		push_error("FAIL: " + label)
		fails += 1
	else:
		print("ok: " + label)


## Fixtures are deterministic by default (slice 36: a flaky suite makes every
## green claim unfalsifiable). Pass a "seed" in cfg, or seed_it=false, to opt
## out — only for a test that genuinely wants variance.
const DEFAULT_SEED := 1


func _boot(cfg: Dictionary, seed_it: bool = true) -> Node2D:
	if seed_it and not cfg.has("seed"):
		cfg = cfg.duplicate()
		cfg.seed = DEFAULT_SEED
	GameScript.next_config = cfg
	GameScript.is_scenario = true
	var game: Node2D = load("res://scenes/Game.tscn").instantiate()
	root.add_child(game)
	return game


func _init() -> void:
	check(Waves.WAVES.size() == 200, "150 designed waves + the generated tail to 200")

	# Kings at 50/100/150/200, with the catalog escorts. The loop below keys on
	# `n % 50 == 0`, so the fourth King wave satisfies it without a special case.
	for n in range(1, Waves.WAVES.size() + 1):
		var has_king: bool = Waves.WAVES[n - 1].has("king")
		if n % 50 == 0:
			check(has_king, "wave %d is a King wave" % n)
		elif has_king:
			check(false, "unexpected king in wave %d" % n)
	check(Waves.WAVES[49].size() == 5, "wave 50: King + 4 escorts")
	check(Waves.WAVES[99].size() == 5, "wave 100: King + 4 escorts")
	check(Waves.WAVES[149].size() == 6, "wave 150: King + 5 escorts")

	# Density curve (GDD totals): 5 through wave 69, 6 from wave 70
	var curve_ok := true
	for n in range(51, 70):
		curve_ok = curve_ok and Waves.WAVES[n - 1].size() == 5
	for n in range(70, 150):
		if n % 50 == 0:
			continue
		curve_ok = curve_ok and Waves.WAVES[n - 1].size() == 6
	check(curve_ok, "density curve: 5 (waves 51-69), 6 (waves 70-149)")

	# --- the GENERATED tail, 151-200 (NO-7 slice 1) -------------------------
	# These assert the CONTRACT tools/generate-endless-waves.mjs promises, not
	# the individual rows: the rows are regenerated by turning a constant, and a
	# test that pinned them would have to be rewritten every time the balance
	# pass moves the curve. What must hold is the shape.
	check(Waves.WAVES[199].size() == 6, "wave 200: King + 5 escorts")

	var w := _boot({"board": [], "wave": 1})
	await process_frame
	var defs: Dictionary = w.defs
	var budget := func(n: int) -> int:
		var t := 0
		for id in Waves.WAVES[n - 1]:
			if id != "king":
				t += int(defs[id].value)
		return t

	var counts_ok := true
	var repeats_ok := true
	for n in range(151, 200):
		var roster: Array = Waves.WAVES[n - 1]
		counts_ok = counts_ok and roster.size() >= 3 and roster.size() <= 8
		for id in roster: # BOARD_W is 8; a wider wave only spills to next turn
			if roster.count(id) > 2:
				repeats_ok = false
	check(counts_ok, "generated tail: every wave is 3-8 pieces, never wider than the board")
	check(repeats_ok, "generated tail: at most two of any one piece — variety is the point")

	# Continuous with wave 150, which is what stops the ramp reading as a seam:
	# the old table plateaus at 220-240 and the tail resumes from there.
	check(budget.call(151) >= budget.call(149) - 20,
		"generated tail: wave 151 picks up where the old table left off, no dip")

	# Monotone climb. The COUNT sawtooths on purpose (a heavier mix buys fewer,
	# bigger pieces) but the value budget must only ever go up.
	var climbs := true
	for n in range(152, 200):
		if budget.call(n) < budget.call(n - 1):
			climbs = false
	check(climbs, "generated tail: the value budget never decreases")
	check(budget.call(199) > budget.call(151) * 2,
		"generated tail: the curve actually climbs — 199 is more than double 151")

	# The phase walk ends on end-tier only, right before the King.
	var endgame := true
	for id in Waves.WAVES[198]:
		if int(defs[id].value) < 60:
			endgame = false
	check(endgame, "generated tail: wave 199 is end-tier pieces only")
	w.queue_free()
	await process_frame

	# Tariff schedule: every 10th wave through 150, catalog tiers
	var tiers := {
		10: "Mild", 20: "Mild", 30: "Mild", 40: "Moderate", 50: "Severe",
		60: "Mild", 70: "Mild", 80: "Moderate", 90: "Moderate", 100: "Severe",
		110: "Mild", 120: "Moderate", 130: "Moderate", 140: "Severe", 150: "Severe",
	}
	check(KingAbilities.SCHEDULE.size() == 15, "15 tariff waves")
	for n in tiers:
		check(KingAbilities.SCHEDULE.get(n) == tiers[n], "wave %d tariff is %s" % [n, tiers[n]])

	# --- early-clear bonus: emptying the board before the next wave pays out
	# score + clock scaled by the turns to spare, once per wave (2026-07-07) ---
	var g: Node2D = _boot({"board": [["queen", 0, 2, 2], ["pawn", 1, 2, 4]], "wave": 2})
	await process_frame
	await process_frame
	var clock0: float = g.clock_ms
	g._move_player(Vector2i(2, 2), Vector2i(2, 4)) # capture the last enemy
	var early: int = g._cadence() # cleared with the whole cadence to spare
	check(g.early_clear_awarded, "clearing before the wave flags the bonus")
	check(g.score == (10 + early * Tuning.EARLY_CLEAR_SCORE_PER_TURN) * 10, # issue 57: x10
			# — the capture and the early-clear bonus are separate Economy.earn
			# calls, each independently x10'd by SCORE_MULTIPLIER
		"early clear pays +%d score on top of the capture" \
		% (early * Tuning.EARLY_CLEAR_SCORE_PER_TURN * 10))
	check(g.clock_ms >= clock0 + early * Tuning.EARLY_CLEAR_CLOCK_MS_PER_TURN \
		+ Tuning.TURN_END_CLOCK_BONUS_MS - 500,
		"early clear refills the clock per spare turn")
	while g.state != GameScript.State.PLAYER_TURN: # let the enemy turn finish
		await create_timer(0.1).timeout
	var score_after: int = g.score
	g._on_pass()
	check(g.score == score_after, "the bonus pays only once per wave")
	g.queue_free()
	await process_frame

	# --- The 10-Wave beat (user ruling 2026-09-06): ONE event at the start of
	# waves 11/21/31…, forever. The pick AND the Clock refill; no silent Stock
	# drip and no Score chunk — those used to fire a wave earlier, so the beat
	# was two mechanics wearing one name. Asserting the absences matters as
	# much as the presences: a drip left in place would still leave the suite
	# green if only "the bot restocked" were checked. ---
	var r: Node2D = _boot({"board": [["queen", 0, 2, 2], ["rook", 1, 7, 10]],
		"wave": 10, "score": 300, "clock_s": 100.0})
	await process_frame
	await process_frame
	var clock_beat: float = r.clock_ms
	var stock0: int = r.stock.size()
	var score0: int = r.score
	r._queue_wave(11)
	check(r.pending_reinforce, "clearing wave 10 pends the reinforcement pick")
	check(r.clock_ms == clock_beat + Tuning.CLOCK_REFILL_MS,
		"...and the SAME event refills the Clock by 2 minutes")
	check(r.stock.size() == stock0,
		"...with no silent Stock drip: the pick is the only piece grant left")
	check(r.score == score0,
		"...and no Score chunk: the beat pays Clock and the pick, nothing else")
	r.autoplay = true # bot path: the panel is free, grab the cheapest offers
	r._begin_player_turn()
	check(not r.pending_reinforce, "the bot consumes the pending pick")
	check(r.stock.size() == stock0 + 4 and r.score == score0,
		"the bot restocked for free (stock +%d)" % (r.stock.size() - stock0))

	# a non-beat wave grants neither half of the merged event
	r.pending_reinforce = false
	var clock12: float = r.clock_ms
	r._queue_wave(12)
	check(not r.pending_reinforce and r.clock_ms == clock12,
		"a non-beat wave pends no pick and refills no Clock")

	# `n > 1`: wave 1 satisfies the modulo but has cleared nothing
	r._queue_wave(1)
	check(not r.pending_reinforce, "wave 1 fires nothing — nothing has been cleared yet")

	# the modulo, not the old 4-entry REINFORCE_WAVES list: it runs in Endless
	var clock50: float = r.clock_ms
	r._queue_wave(51)
	check(r.pending_reinforce and r.clock_ms == clock50 + Tuning.CLOCK_REFILL_MS,
		"wave 51 fires the same beat — past the end of the old REINFORCE_WAVES list")
	r.pending_reinforce = false
	var clock140: float = r.clock_ms
	r._queue_wave(141)
	check(r.pending_reinforce and r.clock_ms == clock140 + Tuning.CLOCK_REFILL_MS,
		"and wave 141 too — every 10th wave, forever, deep in Endless")
	r.queue_free()
	await process_frame

	# review pass 2: a spawn landing on a friendly blockader is a real loss and
	# must go through _lose_player_piece — a bare `lost_player += 1` hid it from
	# every loss-triggered Artefact (Satoshi's -2 Gold, wave_lost_ids, Frog…)
	var blk := _boot({"board": [["queen", 0, 2, 1], ["rook", 1, 7, 7],
			["pawn", 0, 0, 11], ["pawn", 0, 1, 11], ["pawn", 0, 2, 11], ["pawn", 0, 3, 11],
			["pawn", 0, 4, 11], ["pawn", 0, 5, 11], ["pawn", 0, 6, 11], ["pawn", 0, 7, 11]],
		"wave": 2, "artefacts": ["satoshi-s-private-key"], "gold": 20})
	await process_frame
	var lost0: int = blk.lost_player
	blk._queue_wave(3) # 3 pawns pend; Satoshi's own on_wave_clear pays out here
	var gold0: int = blk.gold
	WaveLogic.spawn_pending(blk) # every spot is friendly-held: all 3 arrivals capture
	check(blk.lost_player == lost0 + 3 and blk.wave_lost_ids.size() == 3 and blk.gold == gold0 - 6,
		"review pass 2: spawn-row captures count as losses for Artefacts (Satoshi -2 each, wave_lost_ids)")
	blk.queue_free()
	await process_frame

	# ---- NO-26: the WAVE banner never draws outside the board ---------------
	# Reported from the iPad audit as "starts at the LEFT SCREEN EDGE, outside the
	# board, and stops roughly 60 percent of the way across". The banner was never
	# mis-SIZED: its width has always been the board width and its settled
	# position has always been correct. It ENTERED from outside the board, with
	# nothing clipping it -- invisible on a phone, where the board is nearly full
	# width and the overflow falls off-screen, and plainly visible on a tablet,
	# where the board is centred inside wide margins.
	#
	# Swept across the whole entrance rather than sampled at rest, because the
	# defect only exists mid-animation and a t == 1 check would pass either way.
	var bg := _boot({"wave": 1, "board": [["queen", 0, 2, 2], ["rook", 1, 7, 10]]})
	await process_frame
	var viewports := [[1032.0, 1376.0, "iPad Pro 13in portrait"],
		[480.0, 800.0, "the 480x800 design viewport"],
		[1179.0, 2556.0, "a 9:19.5 phone"]]
	for vp in viewports:
		# drive the layout the same way _layout_board does, so the numbers are the
		# real ones rather than a second copy of the formula
		var vw: float = vp[0]
		var vh: float = vp[1]
		# NO-33: call the game's own solver rather than keeping a second copy of
		# the formula here — this copy silently disagreed the moment ADR-0004
		# coupled the tile to ICON.
		bg.tile = bg.board_tile_for(Vector2(vw, vh))
		bg.board_px = Vector2(roundf((vw - bg.tile * Tuning.BOARD_W) / 2.0), bg.HUD_TOP)
		var board_l: float = bg.board_px.x
		var board_r: float = bg.board_px.x + Tuning.BOARD_W * bg.tile
		var escaped: Array = []
		var t := 0.0
		while t <= 1.0001:
			var br: Rect2 = bg._banner_rect(t, 0)
			if br.size.x > 0.0 and (br.position.x < board_l - 0.5 or br.end.x > board_r + 0.5):
				escaped.append([t, br.position.x, br.end.x])
			t += 0.02
		check(escaped.is_empty(),
			"banner stays inside the board [%.0f, %.0f] for the whole entrance on %s, escaped at: %s"
				% [board_l, board_r, vp[2], str(escaped.slice(0, 3))])
		# and the settled banner still spans the board exactly — the clamp must not
		# have quietly shrunk the thing it was bounding
		var settled: Rect2 = bg._banner_rect(1.0, 0)
		check(absf(settled.position.x - board_l) < 0.5 and absf(settled.end.x - board_r) < 0.5,
			"and at rest it spans the board exactly on %s (%.0f..%.0f)"
				% [vp[2], settled.position.x, settled.end.x])
	bg.queue_free()
	await process_frame

	print("---")
	if fails == 0:
		print("ALL WAVE CHECKS OK")
	quit(1 if fails > 0 else 0)
