extends SceneTree
## NO-101: the four literal inv- ids (inv-sergeant, inv-arrow-pawn,
## inv-kirin-plus, inv-kirin-plus-plus) get the inversion glyph; their
## non-inverted counterparts — and everything else on the board, including
## pieces from the ten become-an-existing-piece inversion pairs, which keep
## that piece's own id — do not (Max's ruling 2026-09-16, out of scope).
##
## Boots the real "every piece type, your side" scenario (generated by
## data/scenarios_pieces.gd from pieces.json) rather than hand-rolling a
## board, so this runs against pieces the game's own setup path actually
## placed. Calls `_is_inversion_marked`, the exact predicate `_draw_piece`
## gates the glyph draw on (game.gd), so the check can never drift from what
## gets drawn. A true pixel check needs a window — game.gd's own
## `_screenshot_and_quit` is commented "windowed run required" — so this is
## the headless ceiling; NO-101's PR carries a windowed screenshot as the
## visual proof.
## Run headless:  godot --headless --path game -s tests/test_board_draw.gd

const GameScript := preload("res://scripts/game.gd")
const Scenarios := preload("res://data/scenarios.gd")

const INVERTED := ["inv-sergeant", "inv-arrow-pawn", "inv-kirin-plus", "inv-kirin-plus-plus"]
const COUNTERPARTS := ["sergeant", "arrow-pawn", "kirin-plus", "kirin-plus-plus"]

var fails := 0


func check(cond: bool, label: String) -> void:
	if not cond:
		push_error("FAIL: " + label)
		fails += 1
	else:
		print("ok: " + label)


func _init() -> void:
	# NO-149 renamed this scenario to "ALL PIECES (%d, your side)" — match on
	# "your side" rather than a prefix, since both ALL PIECES boards now share
	# the "ALL PIECES (" lead-in and only the tail distinguishes them.
	var matches: Array = Scenarios.all().filter(
		func(e: Dictionary) -> bool: return e.name.contains("your side"))
	check(matches.size() == 1, "exactly one 'every type, your side' scenario exists")
	if matches.size() != 1:
		quit(1)
		return
	var cfg: Dictionary = matches[0].cfg.duplicate()
	cfg.seed = 1
	GameScript.next_config = cfg
	GameScript.is_scenario = true
	var game: Node2D = load("res://scenes/Game.tscn").instantiate()
	root.add_child(game)
	await process_frame
	await process_frame

	var ids_on_board := {}
	for pos in game.board:
		ids_on_board[game.board[pos].id] = true

	for id in INVERTED:
		check(ids_on_board.has(id), "scenario board carries %s" % id)
		check(game._is_inversion_marked(id), "%s is marked" % id)
	for id in COUNTERPARTS:
		check(ids_on_board.has(id), "scenario board carries %s" % id)
		check(not game._is_inversion_marked(id), "%s (non-inverted) is NOT marked" % id)

	game.queue_free()
	await process_frame

	print("---")
	if fails == 0:
		print("ALL BOARD-DRAW CHECKS OK")
	quit(1 if fails > 0 else 0)
